### ISSUE TITLE
Problem linking to static library with C-API's under mingw64

### ISSUE THREAD

**Issue by jhmaloney** [blend2d/blend2d#127]
I built blend2D under MinGW-64 (gcc 11.2.0) with:
```
cmake -G "MSYS Makefiles" .. -DCMAKE_BUILD_TYPE=Release -DBLEND2D_STATIC=true
cmake --build .

```

That succeeded and apparently built the static library library:
`-rw-r--r-- 1 John None 2261200 Jan 10 12:56 libblend2d.a`

However when I attempt to use library with this command:

```
gcc -O3 -DNDEBUG -I ../blend2d/src \
	blend2DPerf.c \
	libblend2d.a \
	-lm -lpthread -lstdc++ -lz \
	-o blend2DCairoPerf

```
 I get these link errors:

```
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\cc0vyiY0.o:blend2DPerf.c:(.text+0x48): undefined reference to `__imp_blPathInit'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\cc0vyiY0.o:blend2DPerf.c:(.text+0x57): undefined reference to `__imp_blPathClear'
...
collect2.exe: error: ld returned 1 exit status

```

I think it is finding libblend2d.a, which I move to the same folder as test program.

The same build process and test program works on Ubuntu 18.04 (both 32-bit and 64-bit) and on MacOS, so I suspect the issue has something to do with the mingw64 toolchain I'm using on Windows.

One other strange thing is that ldd doesn't seem to be able the read the .a file; it says "bad file descriptor".

Any suggestions?

**Comment by kobalicek** [comment]
What would it do if you add `-DBL_STATIC` ?

**Comment by jhmaloney** [comment]
That works! Thank you! (Right after I posted my issue I went back and read the instructions on the build page and the need for -DBL_STATIC in the calling program is well documented. Apologies for bothering you with this!

**Comment by kobalicek** [comment]
No worries, that happens :)
